# Generated by Django 5.2.8 on 2025-12-06 01:49

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(db_column='domicilio_id', primary_key=True, serialize=False)),
                ('street', models.CharField(db_column='calle', max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='fecha_registro')),
                ('reference', models.TextField(blank=True, db_column='referencia', null=True)),
            ],
            options={
                'db_table': 'domicilio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(db_column='distrito_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='nombre', max_length=45)),
            ],
            options={
                'db_table': 'distrito',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EnrollmentStatus',
            fields=[
                ('id', models.AutoField(db_column='estado_id', primary_key=True, serialize=False)),
                ('status_name', models.CharField(db_column='estado_nombre', max_length=30, unique=True)),
            ],
            options={
                'db_table': 'cat_estado_alum',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(db_column='sexo_id', primary_key=True, serialize=False)),
                ('gender_name', models.CharField(db_column='sexo_nombre', max_length=20, unique=True)),
            ],
            options={
                'db_table': 'sexo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(db_column='provincia_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='nombre', max_length=45)),
            ],
            options={
                'db_table': 'provincia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(db_column='region_id', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='nombre', max_length=30, unique=True)),
            ],
            options={
                'db_table': 'region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(db_column='alumno_id', primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(db_column='alumno_uuid', default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(db_column='codigo_alumno', max_length=30, unique=True)),
                ('first_name', models.CharField(db_column='nombres', db_index=True, max_length=50)),
                ('paternal_surname', models.CharField(db_column='apellido_paterno', db_index=True, max_length=50)),
                ('maternal_surname', models.CharField(db_column='apellido_materno', max_length=50)),
                ('birth_date', models.DateField(db_column='fecha_nacimiento')),
                ('email', models.CharField(blank=True, db_column='email', max_length=100, null=True, unique=True)),
                ('phone', models.CharField(blank=True, db_column='celular', max_length=20, null=True)),
                ('weight', models.DecimalField(blank=True, db_column='peso', decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('height', models.DecimalField(db_column='estatura', decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('national_id', models.CharField(db_column='dni', max_length=12, unique=True)),
                ('is_active', models.BooleanField(db_column='activo', default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='fecha_registro')),
            ],
            options={
                'db_table': 'alumno',
                'managed': False,
            },
        ),
    ]
