# Generated by Django 5.2.8 on 2025-12-05 21:03

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('alumno_id', models.AutoField(primary_key=True, serialize=False)),
                ('alumno_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('codigo_alumno', models.CharField(max_length=30, unique=True)),
                ('nombres', models.CharField(db_index=True, max_length=50)),
                ('apellido_paterno', models.CharField(db_index=True, max_length=50)),
                ('apellido_materno', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('email', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('celular', models.CharField(blank=True, max_length=20, null=True)),
                ('peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('estatura', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('dni', models.CharField(max_length=12, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'alumno',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatEstadoAlum',
            fields=[
                ('estado_id', models.AutoField(primary_key=True, serialize=False)),
                ('estado_nombre', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'cat_estado_alum',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('distrito_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'distrito',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('domicilio_id', models.AutoField(primary_key=True, serialize=False)),
                ('calle', models.CharField(max_length=45)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('referencia', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'domicilio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('provincia_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'provincia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'db_table': 'region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('sexo_id', models.AutoField(primary_key=True, serialize=False)),
                ('sexo_nombre', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'sexo',
                'managed': False,
            },
        ),
    ]
