# Generated by Django 5.2.8 on 2025-12-06 01:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('evaluation_id', models.AutoField(db_column='evaluacion_id', primary_key=True, serialize=False)),
                ('planned_date', models.DateField(db_column='fecha_planificada')),
                ('description', models.TextField(blank=True, db_column='descripcion', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('name', models.CharField(db_column='nombre', max_length=30)),
                ('evaluation_code', models.CharField(db_column='codigo_evaluacion', max_length=30, unique=True)),
            ],
            options={
                'db_table': 'evaluacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EvaluationStatus',
            fields=[
                ('status_id', models.AutoField(db_column='estado_id', primary_key=True, serialize=False)),
                ('status_name', models.CharField(db_column='estado_nombre', max_length=20, unique=True)),
            ],
            options={
                'db_table': 'cat_estado_eval',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EvaluationStudent',
            fields=[
                ('evaluation_student_id', models.AutoField(db_column='evaluacion_alumno_id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'evaluacion_alumno',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EvaluationType',
            fields=[
                ('type_id', models.AutoField(db_column='tipo_id', primary_key=True, serialize=False)),
                ('type_name', models.CharField(db_column='tipo_nombre', max_length=30, unique=True)),
            ],
            options={
                'db_table': 'cat_tipo_eval',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('exercise_id', models.AutoField(db_column='ejercicio_id', primary_key=True, serialize=False)),
                ('exercise_name', models.CharField(db_column='ejercicio_nombre', max_length=30, unique=True)),
                ('unit', models.CharField(blank=True, db_column='unidad', max_length=15, null=True)),
                ('is_active', models.BooleanField(db_column='activo', default=True)),
            ],
            options={
                'db_table': 'ejercicio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FixedCriteria',
            fields=[
                ('fixed_criteria_id', models.AutoField(db_column='criterio_fijo_id', primary_key=True, serialize=False)),
                ('exact_value', models.DecimalField(db_column='valor_exacto', decimal_places=2, max_digits=6)),
                ('grade', models.DecimalField(db_column='calificacion', decimal_places=2, max_digits=4)),
            ],
            options={
                'db_table': 'criterios_fijo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PhysicalEvaluation',
            fields=[
                ('physical_eval_id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('grade', models.DecimalField(blank=True, db_column='calificacion', decimal_places=2, max_digits=5, null=True)),
                ('observations', models.TextField(blank=True, db_column='observaciones', null=True)),
                ('result', models.DecimalField(blank=True, db_column='resultado', decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'evaluacion_fisica',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RangeCriteria',
            fields=[
                ('range_criteria_id', models.AutoField(db_column='criterios_rango_id', primary_key=True, serialize=False)),
                ('min_value', models.DecimalField(db_column='valor_min', decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_value', models.DecimalField(db_column='valor_max', decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('grade', models.DecimalField(db_column='calificacion', decimal_places=2, max_digits=4)),
            ],
            options={
                'db_table': 'criterios_rango',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TheoryConfig',
            fields=[
                ('config_id', models.AutoField(db_column='config_id', primary_key=True, serialize=False)),
                ('config_name', models.CharField(db_column='config_nombre', max_length=30, unique=True)),
                ('total_questions', models.IntegerField(db_column='total_preguntas')),
                ('notes', models.TextField(blank=True, db_column='notas', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='fecha_creacion')),
                ('is_active', models.BooleanField(db_column='activo', default=True)),
            ],
            options={
                'db_table': 'config_teorica',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TheoryEvaluation',
            fields=[
                ('theory_eval_id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('attempt_number', models.IntegerField(db_column='intento_num')),
                ('performed_at', models.DateField(blank=True, db_column='fecha_realizacion', null=True)),
                ('grade', models.DecimalField(blank=True, db_column='calificacion', decimal_places=2, max_digits=5, null=True)),
                ('observations', models.TextField(blank=True, db_column='observaciones', null=True)),
                ('result', models.IntegerField(blank=True, db_column='resultado', null=True)),
            ],
            options={
                'db_table': 'evaluacion_teorica',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TheoryEvaluationConfig',
            fields=[
                ('theory_eval_config_id', models.AutoField(db_column='evaluacion_config_id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'eval_config_teorica',
                'managed': False,
            },
        ),
    ]
